Partial Italian translation
gbdev/gb-asm-tutorial pull request #32
Opened 2022-10-09 06:59 UTC by Street-Philosopher

first few files of the Italian translation. It has all of the files of src copied in a separate folder (`translations/it/`), but only some have been translated already

2022-11-02 19:33 UTC, avivace requested changes
@ISSOtm Are we sure we need the images copied over when submitting translations?

2023-03-07 10:39 UTC, avivace commented
Hey @Street-Philosopher , we finally moved to Crowdin and I started porting your translation there. Would it be possible for you to create and account there and give me your name? It's way easier to contribute to translations there, gradually approving those and being able to update them with time. 

https://crowdin.com/project/gb-asm-tutorial

2023-03-09 14:16 UTC, avivace commented on translations/it/roadmap.md
> +# Struttura del tutorial
note for translators: this file has been ported to crowdin.

2023-03-09 14:23 UTC, avivace commented on translations/it/part1/toolchain.md
> +# Gli strumenti
note for translators: this file has been ported to crowdin.

2023-03-09 14:32 UTC, avivace commented on translations/it/help-feedback.md
> +# Aiuto e suggerimenti
note for translators: this file has been ported to crowdin.

2023-03-10 22:29 UTC, avivace commented on translations/it/part1/assembly.md
> +:::
note for maintainers: ported to crowdin till here

2023-04-03 06:38 UTC, Street-Philosopher commented
Hi @avivace very sorry if it took me this long to respond.

I just signed up. My username is still `Street-Philosopher`. Thank you!

2023-04-03 06:50 UTC, avivace commented
> Hi @avivace very sorry if it took me this long to respond.
> 
> I just signed up. My username is still `Street-Philosopher`. Thank you!

Amazing, thanks a lot! I just invited you to the project. I hope that's clear enough for you to start contributing there. I ported most of your translations you made in this PR. Feel free to come back for any doubt (here on in another issue).

I will close this PR.

2023-04-03 06:50 UTC, closed without merging