Part II, Lesson 4
gbdev/gb-asm-tutorial pull request #37
Opened 2023-01-03 00:17 UTC by eievui5

Closes #15

2023-01-03 00:17 UTC, eievui5 commented
At the moment this only implements ball movement, not bouncing.

2023-01-05 17:26 UTC, ISSOtm commented
The current code looks fine to me.

2023-01-08 17:39 UTC, avivace commented
What are we missing here? The text part? @eievui5 do you have any update on this?

2023-01-08 17:41 UTC, eievui5 commented
We're missing the ball bouncing against the walls and the paddle, and the text.

2023-01-10 17:48 UTC, eievui5 commented
I'd like some feedback on the bouncing code. The pixel -> tilemap function might be too complex for the tutorial but I'm not sure how else to write it. Otherwise, I think this is pretty understandable :)

2023-01-11 20:41 UTC, ISSOtm requested changes
Alright, the logic seems correct, I just hope we won't start overflowing VBlank time... ><

2023-01-11 20:41 UTC, ISSOtm commented on unbricked/collision/main.asm
> +	; (8, 16) in OAM coordinates is (0, 0) on the tilemap.
```suggestion
	; (8, 16) in OAM coordinates is (0, 0) on the screen.
```

2023-01-11 20:41 UTC, ISSOtm commented on unbricked/collision/main.asm
> +	ld a, 100 + 16
How about using the `hardware.inc` constants instead?

2023-01-11 20:41 UTC, ISSOtm commented on unbricked/collision/main.asm
> +	cp a, $00
What are those IDs about?

2023-01-11 21:24 UTC, eievui5 commented on unbricked/collision/main.asm
> +	cp a, $00
Those are all of the tiles that border the playfield + the bricks.

2023-01-11 21:25 UTC, eievui5 commented on unbricked/collision/main.asm
> +	; (8, 16) in OAM coordinates is (0, 0) on the tilemap.
This isn’t accurate because the function is converting a tilemap position not a… screen position?

2023-01-11 22:44 UTC, ISSOtm commented on unbricked/collision/main.asm
> +	cp a, $00
Ah, right. How about introducing carry comparisons, then?

2023-01-11 22:49 UTC, ISSOtm commented on unbricked/collision/main.asm
> +	; (8, 16) in OAM coordinates is (0, 0) on the tilemap.
We are converting to parameters for `GetTileByPixel`, which appears take screen positions?

2023-01-11 22:52 UTC, eievui5 commented on unbricked/collision/main.asm
> +	; (8, 16) in OAM coordinates is (0, 0) on the tilemap.
Oh yeah. Okay, that makes sense

2023-01-11 22:53 UTC, eievui5 commented on unbricked/collision/main.asm
> +	cp a, $00
Well because you’ll notice they’re not continuous and i don’t think it’s a good idea to reorder them at this point. But maybe it’s worth it for carry

2023-01-11 22:54 UTC, ISSOtm commented on unbricked/collision/main.asm
> +	cp a, $00
I actually did a double-take to try and find a discontinuity, because I didn't expect *you* of all people to pull off a `GetForestTreeFrame` :P

So I think it would help, here.

2023-01-11 22:58 UTC, eievui5 commented on unbricked/collision/main.asm
> +	cp a, $00
Okay. My only issue is that this would be a “breaking change” for anyone who followed the tutorial in the past and is catching up on the new chapter

2023-01-11 22:58 UTC, Rangi42 commented on unbricked/collision/main.asm
> +	ld a, %11100100
@ISSOtm If you're okay with the redundant `ld`, I think the `IsWallTile` `cp`s are fine in comparison. (They're trivial to add/remove individual tile IDs from.)

2023-01-11 23:00 UTC, ISSOtm commented on unbricked/collision/main.asm
> +	cp a, $00
Oh, I was only saying to use a carry comparison for the contiguous IDs, and tack on the final `cp $09`.

2023-01-11 23:00 UTC, ISSOtm commented on unbricked/collision/main.asm
> +	ld a, %11100100
Didn't we discuss that this one should be removed?

2023-01-11 23:02 UTC, eievui5 commented on unbricked/collision/main.asm
> +	ld a, %11100100
iirc ISSO wanted to remove that `ld` actually. While being able to remove the IDs from IsWallTile, I can just reorder the tiles such that the last two are the bricks, and then in the next chapter reduce the constant by two. *Or*, just remove the bricks from the list until then.

2023-01-11 23:03 UTC, ISSOtm commented on unbricked/collision/main.asm
> +	ld a, %11100100
I think removing the bricks is acceptable for now. Especially since we won't be able to just rely on the tile ID for the bounce direction anymore.

2023-01-11 23:04 UTC, eievui5 commented on unbricked/collision/main.asm
> +	cp a, $00
What about the missing `$03`? did you miss that?

2023-01-11 23:04 UTC, ISSOtm commented on unbricked/collision/main.asm
> +	cp a, $00
Yep!

2023-01-11 23:05 UTC, eievui5 commented on unbricked/collision/main.asm
> +	cp a, $00
Without reordering these, I don't see a point in using carry, and I'd rather leave it like this.

2023-01-11 23:06 UTC, eievui5 commented on unbricked/collision/main.asm
> +	cp a, $00
Yes, it would be a bit faster, but interleaving `a != 3 && a <= 7 || a == 9` is kinda needless.

2023-01-11 23:10 UTC, eievui5 commented on unbricked/collision/main.asm
> +	ld a, 100 + 16
Using hardware.inc for what? You mean like `SCRN_Y / 2`?

2023-01-12 03:25 UTC, eievui5 commented
The text and code is now complete.

2023-01-12 09:01 UTC, avivace reviewed
Wow, this actually reads very smoothly! I just left some minor comments and suggestions and will go over it again later.

2023-01-12 12:56 UTC, eievui5 commented on src/part2/collision.md
> +Just like with the paddle, the first step is to create a graphic for the ball and load it into VRAM.
"create a tile" could work

2023-01-14 09:12 UTC, ISSOtm requested changes
Great work! I only have some clean-up suggestions.

Additionally, I would prefer if the Z flag was capitalised, for consistency with the "flags" lesson. (The rationale there was to avoid confusion with the c register.)

And maybe we could link back to some previous lessons, if they are relevant.

2023-01-14 09:12 UTC, ISSOtm commented on unbricked/collision/main.asm
> +	jp nc, PaddleBounceDone
I think the X position check is easier to understand and explain if done the other way around:
```suggestion
	ld a, [_OAMRAM + 5] ; Ball's X position.
	ld b, a
	ld a, [_OAMRAM + 1] ; Paddle's X position.
	sub a, 8
	cp a, b
	jp c, PaddleBounceDone
	add a, 8 + 16 ; 8 to undo, 16 as the width.
	cp a, b
	jp nc, PaddleBounceDone
```

I will also make a diagram to accompany the textual explanation, once a solution is agreed upon.

2023-01-14 09:12 UTC, ISSOtm commented on src/part2/collision.md
> +If you'd prefer to make this easier or more difficult, feel free to adjust the values!
```suggestion
::: note

You might be wondering why we checked 16 pixels to the right but only 8 pixels to the left.
Remember that OAM positions represent the upper-*left* corner of a sprite, so the center of our paddle is actually 4 pixels to the right of the position in OAM.
When you consider this, we're actually checking 12 pixels out on either side from the center of the paddle.

12 pixels might seem like a lot, but it gives some tolerance to the player in case their positioning is off.
If you'd prefer to make this easier or more difficult, feel free to adjust the values!

:::
```

2023-01-14 09:12 UTC, ISSOtm commented on unbricked/collision/main.asm
> +	ld a, 100 + 16
I was thinking of [`OAM_Y_OFS` and `OAM_X_OFS`](https://github.com/gbdev/hardware.inc/blob/225e671a9eb1f81c90e0cc17d29e59c6983657db/hardware.inc#L1040-L1041).

Maybe we can introduce those in an intermediate "cleanup" lesson, where we would introduce constants, and split `main.asm` into several files? (It's getting quite bulky.)

2023-01-14 09:22 UTC, zlago commented
> Additionally, I would prefer if the Z flag was capitalised, for consistency with the "flags" lesson. (The rationale there was to avoid confusion with the c register.)

may i ask why you wont state that theyre called `Z`/`C`, but that the tutorial will refer to them as `zf`/`cf` (or `z`/`cy`) to avoid confusion with registers?

2023-01-14 09:25 UTC, ISSOtm commented
I just went with common practice. Using one of these names would probably help (and `cf`/`cy` might help avoid the `rrca`/`rra` confusion), but I don't want to have to go back to previous lessons as well :smiling_face_with_tear:

2023-01-14 21:00 UTC, avivace commented on src/part2/collision.md
> +We'll need to initialize these, so let's so do right after we write the ball to OAM.
I think this lesson is "loaded" enough, let's do that in one of the following lessons.

2023-01-14 21:00 UTC, avivace commented on src/part2/collision.md
> +
Agree

2023-01-14 22:10 UTC, eievui5 commented on unbricked/collision/main.asm
> +	jp nc, PaddleBounceDone
A diagram would be great, I considered doing it in text but figured an explanation would be enough

2023-01-14 22:11 UTC, eievui5 commented on unbricked/collision/main.asm
> +	ld a, 100 + 16
that works for me

2023-01-14 22:13 UTC, eievui5 commented on src/part2/collision.md
> +Let's create two new variables to track the ball's momentum in the two axis: `wBallMomentumX` and `wBallMomentumY`.
Honestly I prefer the original wording ("in each axis"); "axes" is quite uncommon.

2023-01-14 22:46 UTC, ISSOtm requested changes
Some minor changes, and then I'll have to make the explanation diagram for the last paragraph.

2023-01-14 22:46 UTC, ISSOtm commented on src/part2/collision.md
> +This way, we can check which tile our ball is touching so that we know when to bounce!
```suggestion
::: tip

Please do not get stuck on the details of this next function, as it uses some techniques and instructions we haven't discussed yet.
The basic idea is that it converts the position of the sprite to a location on the tilemap.
This way, we can check which tile our ball is touching so that we know when to bounce!

:::

```

2023-01-14 22:46 UTC, ISSOtm commented on src/part2/collision.md
> +If the target tile ID (in `a`) matches one of the wall tile IDs, the corresponding `cp` will leave `Z` set; if so, we return immediately (via `ret Z`), with `Z` set.
```suggestion
If the target tile ID (in `a`) matches one of the wall tile IDs, the corresponding `cp` will leave `Z` set; if so, we return immediately (via `ret z`), with `Z` set.
```

2023-01-14 22:46 UTC, ISSOtm commented on src/part2/collision.md
> +However, we'll need to cover a new concept: the *carry* flag.
```suggestion
However, for these, we will need [the *carry* flag](../part1/operations.md#flags).
```

2023-01-14 22:46 UTC, ISSOtm commented on src/part2/collision.md
> +Carry is represented by a `C`, like how zero is a `Z`, but don't get it confused with the `c` register!
```suggestion
The carry flag is notated as `C`, like how the zero flag is notated as `Z`, but don't confuse it with the `c` register!
```

2023-01-14 22:46 UTC, ISSOtm commented on src/part2/collision.md
> +(If you want to check `a <= b` or `a > b`, you can use `Z` and `C` in tandem with two `jp` instructions)
```suggestion
::: tip A refresher on comparisons

Just like `Z`, you can use the carry flag to jump conditionally.
However, while `Z` is used to check if two numbers are equal, `C` can be used to check if a number is greater than or smaller than another one.
For example, `cp a, b` sets `C` if `a < b`, and clears it if `a >= b`.
(If you want to check `a <= b` or `a > b`, you can use `Z` and `C` in tandem with two `jp` instructions.)

:::
```

2023-01-14 22:47 UTC, eievui5 commented on src/part2/collision.md
> +If the target tile ID (in `a`) matches one of the wall tile IDs, the corresponding `cp` will leave `Z` set; if so, we return immediately (via `ret Z`), with `Z` set.
I don't like this inconsistency

2023-01-14 22:49 UTC, eievui5 commented
Go ahead :)

2023-01-14 22:58 UTC, ISSOtm commented on src/part2/collision.md
> +If the target tile ID (in `a`) matches one of the wall tile IDs, the corresponding `cp` will leave `Z` set; if so, we return immediately (via `ret Z`), with `Z` set.
It would be inconsistent with the code.

2023-01-14 23:16 UTC, avivace approved these changes

2023-01-21 13:32 UTC, ISSOtm commented
Here are screenshots of the diagram:

![image](https://user-images.githubusercontent.com/15271137/213868857-56c98a64-2834-40b3-a5af-83fadbf1bcd2.png)

![image](https://user-images.githubusercontent.com/15271137/213868893-35d8db7f-cbad-485a-aa36-568aadd048ab.png)

Maybe it should be clarified that we are considering the position of the ball's top-left pixel, though it is highlighted in the above. And, speaking of, going 16 pixels to the right doesn't seem to make much sense given how wide the paddle appears to be. I dunno.

2023-01-21 13:41 UTC, eievui5 commented
> going 16 pixels to the right doesn't seem to make much sense given how wide the paddle appears to be
I’m not sure how much you’ve played around with the physics but i think this has the best feel to it. Any smaller and the player would probably be frustrated by the small paddle size. It might be worth doubling the width of the paddle with another sprite but i don’t think that’s necessary.

2023-01-21 13:43 UTC, ISSOtm commented
Then maybe we should offset the hitbox a bit more to the left, so it's symmetrical?

2023-01-21 14:09 UTC, eievui5 commented
I'd rather just go edit the ball graphic to be one pixel over to the right. Could you update your diagram to reflect that?

2023-01-21 14:10 UTC, ISSOtm commented
Sure, it's just a PNG, you can edit it in `assets/part2`.

2023-01-21 14:13 UTC, eievui5 commented
Thought it was an svg :) should be good now

2023-01-21 19:09 UTC, ISSOtm commented
Alright, that looks good to me. Should we add a "bonus" heading, suggesting how to make the ball bounce when its bottom pixel touches the paddle's? We should suggest "you only need a single instruction!" (`sub a, 6`).

2023-01-21 19:24 UTC, eievui5 commented
Maybe. I like that it kinda sinks in. If we wanna add that in at all then maybe it should just be part of the tutorial itself.

2023-01-21 19:25 UTC, ISSOtm commented
I think it would be beneficial to encourage experimentation, especially if it's just a single instruction.

2023-01-21 19:59 UTC, ISSOtm requested changes
Great!

2023-01-21 19:59 UTC, ISSOtm commented on src/part2/collision.md
> +
```suggestion

Alternatively, you can add `add a, 6` just after `ld a, [_OAMRAM]` instead.

In both cases, try playing with that `6` value, see what feels right!

```

2023-01-21 20:03 UTC, ISSOtm approved these changes

2023-01-22 20:07 UTC, avivace requested changes

2023-01-22 20:07 UTC, avivace commented on src/part2/collision.md
> +::: tip A refresher on comparisons
minor: I really like those boxes!

2023-01-22 20:07 UTC, avivace commented on src/part2/collision.md
> +Alternatively, you can add `add a, 6` just after `ld a, [_OAMRAM]` instead.
Doesn't Alternatively already says what "instead" does? We should pick one only.

2023-01-22 20:10 UTC, eievui5 commented on src/part2/collision.md
> +Please do not get stuck on the details of this next function, as it uses some techniques and instructions we haven't discussed yet.
There is *so much* to explain here that it would take an entire chapter to do so. I don't see any way to explain this without wasting a lot of the reader's time.

2023-01-22 20:17 UTC, eievui5 commented on src/part2/collision.md
> +We need to add collision with the walls so that the ball can bounce around.
I feel like "add collision with the walls" makes sense (the ball will collide with the walls) whereas "add collision detection with the walls" is more confusing (the walls will be used to detect collision?)

2023-01-23 12:28 UTC, ISSOtm commented on src/part2/collision.md
> +Please do not get stuck on the details of this next function, as it uses some techniques and instructions we haven't discussed yet.
All things considered, I think it would make sense to discuss this function in a chapter of its own, since there is so much to discuss.

Considering the way Part II is written, I think we should explain it after introducing it, so that all of the dry concepts and explanations will at least be in a context and goal already known to the reader.

Thus, I think we should dedicate the lesson following this one to that function. Does that seem reasonable?

2023-01-23 12:29 UTC, ISSOtm commented on src/part2/collision.md
> +Alternatively, you can add `add a, 6` just after `ld a, [_OAMRAM]` instead.
I don't think it does, as an alternative could be to only add code. So I think the redundancy here helps clarify the intent.

2023-01-23 12:34 UTC, ISSOtm commented on src/part2/collision.md
> +There's some complexity to doing this, so we're going to make use of two functions.
How about "since the code is somewhat lenghty, we will split some of it out into two functions"?

2023-01-23 12:36 UTC, eievui5 commented on src/part2/collision.md
> +There's some complexity to doing this, so we're going to make use of two functions.
I’ve already changed this to mention that the code needs to be *repeated* a few times.

2023-01-23 12:49 UTC, ISSOtm commented on src/part2/collision.md
> +There's some complexity to doing this, so we're going to make use of two functions.
I blame GitHub Mobile's UI not showing the changes you made since. :( Sorry!

2023-01-26 20:16 UTC, avivace commented on src/part2/collision.md
> +We need to add collision with the walls so that the ball can bounce around.
> I agree with Evie there. Plus, collision is not just detection, it is also reaction.
I'm not following you. For you _adding collision_ is okay , even if it literally doesn't mean anything in plain english but "adding collision detection" is wrong because we should include reaction too? Try to google "collision detection gamedev". In almost every single result to add the "detection" of something also implies (or it's the natural prerequisite) for reacting to it.

> "add collision detection and response"
I don't see how this is complex, especially because this is what we are doing and presenting anyway, so how can the fact that "it's too complex" be a problem at all?

2023-01-26 20:26 UTC, avivace commented on src/part2/collision.md
> +Please do not get stuck on the details of this next function, as it uses some techniques and instructions we haven't discussed yet.
If there is so much to discuss, and if it requires _an entire_ chapter, why exactly are we pushing this to the reader without discussing it beforehand? I don't see any advantage in doing so, except adding complexity in how are the concept presented. What I can propose is to actually write "this chapter that will explain this block" and then we merge/add it here. Eventually maybe this chapter could be split in 2 if it's too long, but I believe that the we definitely exaggerated in the "goal" for this chapter by pushing too much "unexplained" or "ignore this , will be explained" later stuff

2023-01-26 20:28 UTC, eievui5 commented on src/part2/collision.md
> +We need to add collision with the walls so that the ball can bounce around.
It's not really about the use of "detection" so much as the "with the walls" part. If we want to make it say "collision detection", it would have to look like this:
> We need to add collision detection so that the ball can bounce around.
which works.

2023-01-26 20:35 UTC, eievui5 commented on src/part2/collision.md
> +Please do not get stuck on the details of this next function, as it uses some techniques and instructions we haven't discussed yet.
It's simply because all the math and instructions behind this would completely throw off the pacing of the tutorial. Our primary concern at the moment is teaching the logic of assembly and making a game.

I don't think anyone wants to start off "Hello, world!" by explaining all the intricacies of file descriptors and pipes, for example. I would consider this function to be "`#include <stdio.h>`". It would be nice to explain more, but now is not the time.

2023-02-09 18:26 UTC, ISSOtm commented on src/part2/collision.md
> +Please do not get stuck on the details of this next function, as it uses some techniques and instructions we haven't discussed yet.
Showing results and explaining them later has been the entire guiding principle behind Part I, since the gb-asm-tutorial-old showed that the "explain everything first, show results at the end" strategy was ineffective.

I think it also helps making the tutorial feeling more cohesive; think of it as a plot thread/cliffhanger?

Maybe we should reword this info box, however. How about:

> This function uses a lot of concepts we haven't talked about yet.
> We will examine and explain it in the next section; for now, let's assume it does what we want it to.

2023-02-09 18:35 UTC, eievui5 commented on src/part2/collision.md
> +Please do not get stuck on the details of this next function, as it uses some techniques and instructions we haven't discussed yet.
"next section" being part 3?

2023-02-09 18:41 UTC, ISSOtm commented on src/part2/collision.md
> +Please do not get stuck on the details of this next function, as it uses some techniques and instructions we haven't discussed yet.
I meant "next lesson", don't mind me.

2023-02-13 09:28 UTC, avivace approved these changes
I don't agree with the suggested order of presenting things (let alone pushing entire functions/sections of code to the reader) but it's merely an order issue, it can be re-examined later when such explanations are added.

Everything else looks very good

2023-02-18 22:55 UTC, merged