Part II, Lesson 5
gbdev/gb-asm-tutorial pull request #40
Opened 2023-01-13 03:14 UTC by eievui5

Closes #16

2023-01-13 03:15 UTC, eievui5 commented
I'll leave this as a draft until #37 is merged

2023-01-14 09:31 UTC, ISSOtm requested changes
Nice! Something short and simple, for once :sweat_smile:

2023-01-14 09:31 UTC, ISSOtm commented on src/part2/bricks.md
> +
```suggestion

Constants are a kind of *symbol* (which is to say, "a thing with a name").
Writing a constant's name in an expression is equivalent to writing the number the constant is equal to, so `ld a, BRICK_LEFT` is the same as `ld a, $05`.
But I think we can all agree that the former is much clearer, right?

```

2023-01-14 09:31 UTC, ISSOtm commented on src/part2/bricks.md
> +If we hit the left side of a brick (represented by `BRICK_LEFT`), we need to remove it and the tile to the right (which should be the right side).
```suggestion
If we hit the left side of a brick (represented by `BRICK_LEFT`), we need to remove it and the tile to its right (which should be the right side).
```

2023-01-14 09:31 UTC, ISSOtm commented on src/part2/bricks.md
> +Alternatively, if we hit the right side we need to remove the left!
```suggestion
If we instead hit the right side, we need to remove the left!
```

2023-01-15 00:35 UTC, eievui5 commented
Yeah, much less than I expected. Hopefully the review process won't take as long because of that :)

2023-02-08 15:58 UTC, avivace requested changes

2023-02-08 16:41 UTC, avivace commented
I will say it once again: this PR needs to be rebased in order to be properly reviewed. It adds a separate file so it can even be rebased against master and we proceed from there.

2023-02-25 16:58 UTC, closed without merging