Add support for translations
gbdev/gb-asm-tutorial pull request #49
Opened 2023-03-02 21:48 UTC by avivace

Based on the i18n support implemented in https://github.com/google/comprehensive-rust

2023-03-04 11:39 UTC, ISSOtm requested changes
Thank you very much for your help setting this up! I only have suggestions about some details; the overall process is very good!

2023-03-04 11:39 UTC, ISSOtm commented on .github/workflows/build-and-deploy.yml
> +        mv book/it/custom book/custom/it
```suggestion
        mdbook build
        for f in po/*.po; do
            lang="${f%.po}"
            MDBOOK_BOOK__LANGUAGE="$lang" mdbook build -d book/"$lang"
            mv book/"$lang"/custom book/custom/"$lang"
        done
```
This allows adding new languages without touching the CI workflow, and is also a bit more DRY.

2023-03-04 11:39 UTC, ISSOtm commented on .gitignore
> +po/messages.pot
```suggestion
/po/messages.pot
```
I suppose?

2023-03-04 11:39 UTC, ISSOtm commented on README.md
> +```
Two spaces should be added before each of these lines, otherwise the code block breaks the list.

2023-03-04 11:39 UTC, ISSOtm commented on README.md
> +To add a translation or contribute on an existing one, please see [TRANSLATING](TRANSLATING.md).
What about moving this just below the "Contributing" header? This would increase its visibility.

2023-03-04 11:39 UTC, ISSOtm commented on README.md
> +- The code related to the i18n support is originally from Google's [Comprehensive Rust](https://github.com/google/comprehensive-rust) and it's released under the [Apache License 2.0](https://github.c
```suggestion
- The code related to the i18n support is originally from Google's [Comprehensive Rust](https://github.com/google/comprehensive-rust) and is released under the [Apache License 2.0](https://github.com/gbdev/gb-asm-tutorial/blob/master/i18n-helpers/LICENSE).
```

2023-03-04 11:39 UTC, ISSOtm commented on book.toml
> +[preprocessor.gettext]
```suggestion
[preprocessor.links]

[preprocessor.gettext]
```
The built-in `links` preproc is required to expand `{{#include}}`.

That said, this presents an interesting question: in which order should these two run? I.e. should the `include`d text be localised? I'd say no, and then we should add a `before = ["links"]` line to the `[preprocessor.gettext]` table.

2023-03-04 11:39 UTC, ISSOtm commented on po/it.po
> +"Language-Team: Italian <tp@lists.linux.it>\n"
Um, is that right?

2023-03-04 11:39 UTC, ISSOtm commented on theme/index.hbs
> +                          </button></li>
We should probably mention adding this in the "initialising a new translation" section.

2023-03-04 11:39 UTC, ISSOtm commented on TRANSLATING.md
> +```
I'm not a total fan of making people install software globally on their machine, especially due to the possibility of version conflicts. Would it be possible to use a `command` entry instead, like for the other two custom programs we already have? `cargo run -p i18n-helpers --bin mdbook-gettext --locked --release --` should do the trick, I think.

(If we do go through with that, then this paragraph and the corresponding step in CI should be removed.)

2023-03-04 21:38 UTC, avivace commented on README.md
> +To add a translation or contribute on an existing one, please see [TRANSLATING](TRANSLATING.md).
I moved it to its own chapter. It will also have a paragraph about contributing directly on Crowdin.

2023-03-04 21:38 UTC, avivace commented on README.md
> +```
Done

2023-03-04 21:40 UTC, avivace commented on book.toml
> +[preprocessor.gettext]
Agree, I changed as suggested

2023-03-04 21:41 UTC, avivace commented on theme/index.hbs
> +                          </button></li>
Done

2023-03-04 21:41 UTC, avivace commented on po/it.po
> +"Language-Team: Italian <tp@lists.linux.it>\n"
I don't think that line is mandatory, I removed it

2023-03-04 22:00 UTC, avivace commented on TRANSLATING.md
> +```
Done!

2023-03-04 22:33 UTC, ISSOtm requested changes

2023-03-04 22:33 UTC, ISSOtm commented on README.md
> +
Shouldn't this be above the "contributing" header, so it's more prominent?

2023-03-04 22:33 UTC, ISSOtm commented on TRANSLATING.md
> +
I think we should mention Crowdin here. It should have less friction than the whole PR workflow, and so be more successful.

2023-03-04 22:33 UTC, ISSOtm commented on theme/index.hbs
> +                              <a id="it">Italian</a>
Hey, actually, what does clicking this link do?

2023-03-04 22:37 UTC, avivace commented on TRANSLATING.md
> +
I agree  but I suggest doing this in two phases. The crowdin workflow is still not tested yet and I'd feel more comfortable in starting to merge the translation system first then see if crowdin works as a collaborative frontend.

2023-03-04 22:39 UTC, avivace commented on theme/index.hbs
> +                              <a id="it">Italian</a>
It links to the italian version of the current page. 

See demo over: https://avivace.github.io/gb-asm-tutorial/

2023-03-04 22:50 UTC, ISSOtm commented on theme/index.hbs
> +                              <a id="it">Italian</a>
The lack of `href` really tripped me; apparently that's set up via JS, which I really don't like (why not static in the first place?) but I guess it has to do for now.

2023-03-04 22:51 UTC, ISSOtm commented on TRANSLATING.md
> +
Fine by me; then this PR is basically complete.

2023-03-04 23:16 UTC, avivace commented on README.md
> +
done

2023-03-04 23:17 UTC, avivace commented on theme/index.hbs
> +                              <a id="it">Italian</a>
I guess that would require another preprocessor populating the submenu? Feel free to open an issue about it if you feel like it's necessary

2023-03-05 00:29 UTC, ISSOtm approved these changes
That's step 1 done :)

2023-03-05 00:29 UTC, merged

2023-04-05 08:29 UTC, mgeisler commented
Hi folks! Thanks for trying out the i18-helpers, I hope they're useful?

I just wanted to let you know that I've released them as a stand-alone crate now: https://crates.io/crates/mdbook-i18n-helpers. That should let you clean up the code here a bit :slightly_smiling_face: 

I noticed you use `cargo run` directly. With a downloaded crate, you should be able to replace that with `cargo install --root tmp mdbook-i18n-helpers` and then refer to `tmp/bin/mdbook-xgettext` and `tmp/bin/mdbook-gettext` in your `book.toml`.

Please open issues in the repository for any problems you run into. Thanks!

2023-04-08 22:50 UTC, avivace commented
> Hi folks! Thanks for trying out the i18-helpers, I hope they're useful?
> 
> I just wanted to let you know that I've released them as a stand-alone crate now: [crates.io/crates/mdbook-i18n-helpers](https://crates.io/crates/mdbook-i18n-helpers). That should let you clean up the code here a bit slightly_smiling_face
> 
> I noticed you use `cargo run` directly. With a downloaded crate, you should be able to replace that with `cargo install --root tmp mdbook-i18n-helpers` and then refer to `tmp/bin/mdbook-xgettext` and `tmp/bin/mdbook-gettext` in your `book.toml`.
> 
> Please open issues in the repository for any problems you run into. Thanks!

Wow, thanks a lot @mgeisler ! I'll open another issue with the points you mentioned so we can take a look at this later. Thanks again for the amazing translation system, it's working very nice for us!

2023-04-09 21:33 UTC, mgeisler commented
> Thanks again for the amazing translation system, it's working very nice for us!

Thanks for the feedback, I'm very happy it works for you!

2023-08-14 09:39 UTC, mgeisler commented
Hey @avivace, I wanted to let you know about https://github.com/google/mdbook-i18n-helpers/pull/46.

The current `main` branch of mdbook-i18n-helpers has a new text extraction system: it will turn `# Some heading` in the Markdown file into just `"Some heading"` in the PO file. Paragraphs are un-wrapped when extracted. Lists are now extracted on a per-item basis and tables are extracted on a cell-by-cell basis. This removes most of the Markdown syntax and makes the job easier for translators. It also allows you to freely reformat the Markdown files without invalidating the existing translations.

For this to work smoothly with existing translations, I've written a conversion tool: https://github.com/google/mdbook-i18n-helpers/pull/46. When that is merged, I will make a new release. I hope you will be able to migrate to it as well.

Eventually, I want to release a GitHub action for all this: https://github.com/google/mdbook-i18n-helpers/issues/48. That should make your life easier since you can export the complexity back to the mdbook-i18n-helpers repository :smile:

2023-08-14 09:43 UTC, mgeisler commented
I added a link to this projects in the mdbook-i18n-helpers README: https://github.com/google/mdbook-i18n-helpers/pull/49. I hope you don't mind?

2023-08-23 16:58 UTC, mgeisler commented
> This sounds very interesting and cleaning up the strings from formatting is definitely appreciated. Feel free to ping me when the migration tool is ready!

The converter tool is part of the new 0.2 release which I made last week.

I've created PRs for Comprehensive Rust today to update the translations. As an example, the [Brazilian Portuguese page on scalar types](https://google.github.io/comprehensive-rust/pt-BR/basic-syntax/scalar-types.html) is using the new system — the table you see there is translated cell-by-cell. If we change one of them in the English original, the others will remain translated.