SHMUP Tutorial PR
gbdev/gb-asm-tutorial pull request #57
Opened 2023-04-14 23:07 UTC by LaroldsJubilantJunkyard

Adding SHMUP tutorial for the gb-asm-tutorial: Galactic Armada.

Markdown files created for the various parts of the tutorial.
Images, markdown files, and code snippets organized into their own folders.
The summary.md has been updated with all the part 3 sections.

2023-04-17 09:17 UTC, avivace requested changes
Amazing! Thanks a lot @LaroldsJubilantJunkyard ! I've started correcting some typos but I'll go through everything again later.

2023-04-17 09:17 UTC, avivace commented on src/part3/collision.md
> +Collision Detection is cruical to games. It can be a very complicated topic. In Galactic Armada, things will be kept super simple. We're going to perform a basic implementation of "Axis-Aligned Bound
```suggestion
Collision Detection is crucial to games. It can be a very complicated topic. In Galactic Armada, things will be kept super simple. We're going to perform a basic implementation of "Axis-Aligned Bounding Box Collision Detection". From Mozilla, Axis-Aligned Bounding Box Collision Detection is:
```

2023-04-17 09:17 UTC, avivace commented on src/part3/collision.md
> +Collision Detection is cruical to games. It can be a very complicated topic. In Galactic Armada, things will be kept super simple. We're going to perform a basic implementation of "Axis-Aligned Bound
```suggestion
Collision Detection is cruical to games. It can be a very complicated topic. In Galactic Armada, things will be kept super simple. We're going to perform a basic implementation of "Axis-Aligned Bounding Box Collision Detection". From [Mozilla](https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection), Axis-Aligned Bounding Box Collision Detection is:
```

2023-04-17 09:17 UTC, avivace commented on src/part3/collision.md
> +> ~ [Mozilla](https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection)
```suggestion

```

2023-04-17 09:17 UTC, avivace commented on src/part3/collision.md
> +The easiest way to check for overlap, is to check the difference bewteen their centers. If the absolute value of their x & y differences (i'll refer to as "the absolute difference") are BOTH smaller
```suggestion
The easiest way to check for overlap, is to check the difference bewteen their centers. If the absolute value of their x & y differences (I'll refer to as "the absolute difference") are BOTH smaller than the sum of their half widths, we have a collision. This collision detection is run for bullets against enemies, and enemies against the player. Here's a visualization with bullets and enemies.
```

2023-04-17 09:17 UTC, avivace commented on src/part3/getting-started.md
> +[https://github.com/LaroldsJubilantJunkyard/galactic-armada](https://github.com/LaroldsJubilantJunkyard/galactic-armada)
I believe the full example code should be moved to this repository? Or at least under gbdev

2023-04-17 09:17 UTC, avivace commented on src/part3/getting-started.md
> +[https://github.com/LaroldsJubilantJunkyard/galactic-armada](https://github.com/LaroldsJubilantJunkyard/galactic-armada)
The code is missing a LICENSE. @LaroldsJubilantJunkyard , we should release it in the Public Domain as we're doing with the rest of the code referenced in the tutorial

2023-04-17 09:17 UTC, avivace commented on src/part3/heads-up-interface.md
> +That should be all it takes to get a properly drawn HUD. For more details, check out the code in the repo or ask questions on the gbdev discord server. With that done, We can draw text on the window
```suggestion
That should be all it takes to get a properly drawn HUD. For more details, check out the code in the repo or [ask questions](https://gbdev.io/gb-asm-tutorial/help-feedback.html) on the gbdev discord server. With that done, We can draw text on the window similar to how we drew text on the title screen, just passing a different address.
```

2023-04-17 22:57 UTC, LaroldsJubilantJunkyard commented on src/part3/getting-started.md
> +[https://github.com/LaroldsJubilantJunkyard/galactic-armada](https://github.com/LaroldsJubilantJunkyard/galactic-armada)
that's fine. a similar thought popped into my head.

2023-04-25 23:07 UTC, avivace requested changes

2023-04-25 23:07 UTC, avivace commented on src/SUMMARY.md
>  # Part Ⅲ — Our second game
```suggestion
# Part III — Our second game
```

2023-04-25 23:07 UTC, avivace commented on src/assets/part3/img/EnemyBytesVisualized.png
Do you have a "source" for these assets? E.g. project files that can be modified (e.g. gimp's XCFs)

2023-04-26 01:38 UTC, LaroldsJubilantJunkyard commented on src/assets/part3/img/EnemyBytesVisualized.png
I have aseprite files in the repo:

https://github.com/LaroldsJubilantJunkyard/galactic-armada/tree/master/src/resources/sprites
https://github.com/LaroldsJubilantJunkyard/galactic-armada/tree/master/src/resources/backgrounds

To be honest though, the PNG can be edited directly. I didn't think about it before, but i could probably remove the aseprite files.

2023-05-09 23:05 UTC, avivace requested changes

2023-05-09 23:05 UTC, avivace commented on src/part3/collision.md
> +> One of the simpler forms of collision detection is between two rectangles that are axis aligned — meaning no rotation. The algorithm works by ensuring there is no gap between any of the 4 sides of
```suggestion
> One of the simpler forms of collision detection is between two rectangles that are axis aligned — meaning no rotation. The algorithm works by ensuring there is no gap between any of the 4 sides of the rectangles. Any gap means a collision does not exist.[^mdn_source]
```

2023-05-09 23:05 UTC, avivace commented on src/part3/collision.md
> +```
```suggestion
\```

[^mdn_source]:
From [mdn web docs - 2D collision detection](https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection)

```

2023-05-09 23:05 UTC, avivace commented on src/part3/collision.md
> +```
I'm not sure how to escape the "```"

2023-05-09 23:05 UTC, avivace commented on src/part3/collision.md
> +> One of the simpler forms of collision detection is between two rectangles that are axis aligned — meaning no rotation. The algorithm works by ensuring there is no gap between any of the 4 sides of
The footnote definition is added on a later suggestion in this review

2023-05-09 23:05 UTC, avivace commented on src/part3/conclusion.md
> +This tutorial was written by Larold at Larold's Jubilant Junkyard. If you're looking for more gameboy game development tutorials, check out [My website](https://www.LaroldsJubilantJunkyard.com) or [M
I think we may want to move Credits/acknowledgments to some starting page or to the current "Thanks"

2023-05-11 07:36 UTC, avivace commented on src/part3/title-screen.md
> +The "DrawTitleScreen" function puts the tiles for our title screen graphic in VRAM, and draws it's titlemap to the background:
```suggestion
The "DrawTitleScreen" function puts the tiles for our title screen graphic in VRAM, and draws its tilemap to the background:
```

2023-05-11 07:38 UTC, avivace commented on src/part3/the-player.md
> +The player’s logic is pretty simple. The player can move 4 directions and fire bullets. When updating the player, we check our input directions and the A button. We’ll move in the proper direction if
```suggestion
The player’s logic is pretty simple. The player can move in 4 directions and fire bullets. We update the player by checking our input directions and the A button. We’ll move in the proper direction if its associated d-pad button is pressed. If the A button was JUST pressed, we’ll spawn a new bullet at the player’s position.
```

2023-05-11 07:40 UTC, avivace commented on src/part3/the-player.md
> +When the player wants to shoot, we first check if the A button previously was down. If it was, we won't shoot a new bullet. This avoids bullet spamming a little. For spawning bullets, we have a funct
```suggestion
When the player wants to shoot, we first check if the A button previously was down. If it was, we won't shoot a new bullet. This avoids bullet spamming a little. For spawning bullets, we have a function called "FireNextBullet". This function will need the new bullet's 8-bit X coordinate and 16-bit Y coordinate, both set in a variable it uses called "wNextBullet"
```

2023-05-11 07:41 UTC, avivace commented on src/part3/the-player.md
> +After we've potentially moved the player and/or shot a new bullet. We need to draw our player. However to create the "flashing" effect when damaged, we'll conditionally NOT draw our player sprite. We
```suggestion
After we've potentially moved the player and/or shot a new bullet. We need to draw our player. However, to create the "flashing" effect when damaged, we'll conditionally NOT draw our player sprite. We do this based on the "wPlayerFlash" variable.
```

2023-05-11 07:41 UTC, avivace commented on src/part3/the-player.md
> +After we've potentially moved the player and/or shot a new bullet. We need to draw our player. However to create the "flashing" effect when damaged, we'll conditionally NOT draw our player sprite. We
"we'll conditionally NOT draw our player sprite."  this sounds a bit overcomplicated

2023-05-11 07:42 UTC, avivace commented on src/part3/the-player.md
> +When the player is damaged by an enemy, we want to decrease our lives by one and start flashing. Later we'll conditionally draw the players metasprite based on that flashing variable. In the gameplay
```suggestion
When an enemy damages the player, we want to decrease our lives by one and start flashing. Later, we'll draw the player's metasprite based on that flashing variable. In the gameplay game state, if we've lost all lives, gameplay will end.
```

2023-05-13 15:06 UTC, LaroldsJubilantJunkyard commented on src/part3/the-player.md
> +After we've potentially moved the player and/or shot a new bullet. We need to draw our player. However to create the "flashing" effect when damaged, we'll conditionally NOT draw our player sprite. We
> 

What would be a recommended alternative?

2023-05-13 15:14 UTC, LaroldsJubilantJunkyard commented on src/assets/part3/img/Untitled.png
ahhh.. forgot about that one. will rename

2023-05-14 16:04 UTC, avivace requested changes

2023-05-14 16:04 UTC, avivace commented on src/part3/title-screen.md
> +The title screen shows a basic title image using the background and draws text for the user to press A. Once the user presses A, it will go to the story screen.
```suggestion
The title screen shows a basic title image using the background and draws text asking the player to press A. Once the user presses A, it will go to the story screen.
```

2023-05-14 16:04 UTC, avivace commented on src/part3/title-screen.md
> +* The "Press a to play" text
```suggestion
* The "Press A to play" text
```

2023-05-14 16:04 UTC, avivace commented on src/part3/title-screen.md
> +In our title screens "InitTitleScreen" function, we'll do the following:
```suggestion
In our title screen's "InitTitleScreen" function, we'll do the following:
```

2023-05-14 16:04 UTC, avivace commented on src/part3/title-screen.md
> +The "DrawTextTilesLoop" function comes from our "src/main/utils/text-utils.asm" class. It draws the text specified in hl, to the background/window address specified in de.  With that function created
```suggestion
The "DrawTextTilesLoop" function comes from our "src/main/utils/text-utils.asm" file. It draws the text specified in hl, to the background/window address specified in `de`.  With that function created. Drawing the ‘press A to play’ at the background tilemap tile $99C3, is an easy task. We just need to call the function. Passing the starting address as `de`, and addresses to the actual text in `hl`. 
```

2023-05-14 16:04 UTC, avivace commented on src/part3/title-screen.md
> +Our "WaitForKeyFunction" is is defined in "src/main/utils/input-utils.asm". We'll poll for input and infinitely loop until the speicified button is pressed down.
```suggestion
Our "WaitForKeyFunction" is defined in "src/main/utils/input-utils.asm". We'll poll for input and infinitely loop until the specified button is pressed down.
```

2023-05-14 16:04 UTC, avivace commented on src/part3/the-player.md
> +When an enemy damages the player, we want to decrease our lives by one and start flashing. Later, we'll draw the player's metasprite based on that flashing variable. In the gameplay game state, if we
"flashing variable" is a bit unclear here and was not explained/introduced before, do you mean a variable keeping the information "are we flashing?"

2023-05-14 16:04 UTC, avivace commented on src/part3/the-player.md
> +Here's what our "InitializePlayer" function looks like below. Recall, this was called when initiating the gameplay game state:
> 
```suggestion
Here's what our "InitializePlayer" function looks like. Recall, this was called when initiating the gameplay game state:
```

Why "below" here?

2023-05-15 22:25 UTC, avivace requested changes

2023-05-15 22:25 UTC, avivace commented on src/part3/title-screen.md
> +* draw our "press a to play"
```suggestion
* draw our "Press A to play"
```

2023-05-15 22:25 UTC, avivace commented on src/part3/title-screen.md
> +The "DrawTextTilesLoop" function comes from our "src/main/utils/text-utils.asm" file. It draws the text specified in hl, to the background/window address specified in `de`.  With that function create
This line feels very repetitive, it needs rewording e.g.the de/hl thing is repeated twice and we say we create the function to do X, then we say to do X we just need to call the function

2023-05-15 22:25 UTC, avivace commented on src/part3/the-player.md
> +That's everything for our player. Next we'll go over bullets, and then onto the enemies.
```suggestion
That's everything for our player. Next, we'll go over bullets and then onto the enemies.
```

2023-05-15 22:25 UTC, avivace commented on src/part3/the-player.md
> +The player’s logic is pretty simple. The player can move in 4 directions and fire bullets. We update the player by checking our input directions and the A button. We’ll move in the proper direction i
```suggestion
The player’s logic is pretty simple. The player can move in 4 directions and fire bullets. We update the player by checking our input directions and the A button. We’ll move in the proper direction if its associated d-pad button is pressed. If the A button is pressed, we’ll spawn a new bullet at the player’s position.
```

2023-05-15 22:25 UTC, avivace commented on src/part3/story-screen.md
> +The next & final game state to cover is gameplay. This has the biggest amount of logic and source files, so it will be orgnized into sub pages on the sidebar.
```suggestion

```

I don't think this "warning" here it's useful. Navigation happens anyway in "sub pages in the sidebar", so I'm not sure what we're trying to convey here

2023-05-15 22:25 UTC, avivace commented on src/part3/story-screen.md
> +The next & final game state to cover is gameplay. This has the biggest amount of logic and source files, so it will be orgnized into sub pages on the sidebar.
Also, it was already said that the "final game state will be gameplay" (just the paragraph above)

2023-05-15 22:25 UTC, avivace commented on src/part3/story-screen.md
> +With our story full shown, we're ready to move onto the next game state: Gameplay. We'll end our "UpdateStoryState" function by updating our game state variable and jump back to the "NextGameState" l
```suggestion
With our story fully shown, we're ready to move on to the next game state: Gameplay. As previously discussed, we'll end our "UpdateStoryState" function by updating our game state variable and returning to the "NextGameState" label.
```

2023-05-15 22:25 UTC, avivace commented on src/part3/story-screen.md
> +Getting back to our Story Screen: After we've shown the first page and cleared the background, we'll do the same thing for page2:
```suggestion
Getting back to our Story Screen: After we've shown the first page and cleared the background, we'll do the same thing for page 2:
```

2023-05-15 22:25 UTC, avivace commented on src/part3/story-screen.md
> +We use that function in the "UpdateStoryState" function, by setting two things:
"We use a that function in the function" feels confusing here

2023-05-15 22:25 UTC, avivace commented on src/part3/story-screen.md
> +The story text is shown using a typewriter effect. This effect is done the same way the “press a to play” text was done before. Except, we are waiting 3 vertical blank phases between writing each let
```suggestion
The story text is shown using a typewriter effect. This effect is done similarly to the “press a to play” text that was done before, but here we wait for 3 vertical blank phases between writing each letter, giving some additional delay.
```

2023-05-15 22:25 UTC, avivace commented on src/part3/story-screen.md
> +The "InitStoryState" does not have any logic in it. We're just going to turn on the LCD and that's it. The reason for this is that most of this game state's logic will occur in it's update function.
```suggestion
In the "InitStoryState" we'll just going to turn on the LCD. Most of the game state's logic will occur in its update function.
```

2023-05-15 22:25 UTC, avivace commented on src/part3/story-screen.md
> +The story screens shows a basic generic story on 2 pages. Afterwards it sends the player to the gameplay game state.
```suggestion
The story screen shows a basic story on 2 pages. Afterwards, it sends the player to the gameplay game state.
```

2023-05-16 13:12 UTC, avivace requested changes

2023-05-16 13:12 UTC, avivace commented on src/part3/spawning-enemies.md
> +For spawning enemies, we increase a counter each frame. When this counter reaches a set value, we’ll TRY to spawn an enemy. If an enemy is actual spawned, we’ll reset the counter. When trying to spaw
```suggestion
For spawning enemies, we increase a counter each frame. When this counter reaches a set value, we’ll TRY to spawn an enemy. If this succeds, we’ll reset the counter. When trying to spawn a value, we’ll get a random unsigned 8-bit number. This number will be the enemies x position.
```

TODO: "From: [https://github.com/pinobatch/libbet/blob/master/src/rand.z80#L34-L54](https://github.com/pinobatch/libbet/blob/master/src/rand.z80#L34-L54)" should go in a reference at the bottom

2023-05-16 13:12 UTC, avivace commented on src/part3/scrolling-background.md
> +>⚠️ Scaled Integers are a way to provide smooth “sub-pixel” movement. They are slightly more difficult to understand & implement than implementing a counter, but they provide smoother motion.
It would be nice to add a reference here for "Scaled Integers", e.g. : https://en.wikipedia.org/wiki/Scale_factor_(computer_science)

2023-05-16 13:12 UTC, avivace commented on src/part3/project-structure.md
> +Compilation is done via a Makefile. This makefile can be run using the `make` command. Make should be preinstalled on linux and Mac systems. For windows users, check out [cygwin](https://www.cygwin.c
```suggestion
Compilation is done via a Makefile. This makefile can be run using the `make` command. Make should be preinstalled on Linux and Mac systems. For Windows users, check out [cygwin](https://www.cygwin.com/).
```

2023-05-16 13:12 UTC, avivace commented on src/part3/project-structure.md
> +- Apply the RGBDS “fix” utility for the generated ROM file so everything works fine.
```suggestion
- Apply the RGBDS “fix” utility.
```

Maybe link https://rgbds.gbdev.io/docs/v0.4.2/rgbfix.1/ here?

2023-05-16 13:12 UTC, avivace commented on src/part3/project-structure.md
> +These images were originally created in Aseprite. The original files are included in the repository, but require Aseprite.  They were exported as a PNG **with a specific color palette**. Ater beingex
```suggestion
These images were originally created in Aseprite. The original templates are also included in the repository.  They were exported as a PNG **with a specific color palette**. Ater being exported as a PNG, when you run `make`, they are converted into .2bpp and .tilemap files via the RGBDS tool: RGBGFX.  
```

2023-05-16 13:12 UTC, avivace commented on src/part3/object-pools.md
> +To Activate a pooled object, we simply loop through each object. If the first byte, which tells us if it’s active or not, is 0: then we’ll add the new item at that location and set that byte to be 1.
```suggestion
To activate a pooled object, we simply loop through each object. If the first byte, which tells us if it’s active or not, is 0: then we’ll add the new item at that location and set that byte to be 1. If we loop through all possible objects and nothing is inactive, nothing happens.
```

2023-05-16 13:12 UTC, avivace commented on src/part3/object-pools.md
> +TODO Insert Scaled Integer Articles Link
See other remark about a reference for Scaled Integers

2023-05-16 13:12 UTC, avivace commented on src/part3/object-pools.md
> +2. X - Where they are horizontally
```suggestion
2. X - Position: horizontal coordinate
```

2023-05-16 13:12 UTC, avivace commented on src/part3/object-pools.md
> +2. X - Where they are horizontally
```suggestion
2. X - Position: horizontal coordinate
```

2023-05-16 13:12 UTC, avivace commented on src/part3/object-pools.md
> +5. Speed - How Fast they move
```suggestion
5. Speed - How fast they move
```

2023-05-16 21:24 UTC, LaroldsJubilantJunkyard commented on src/part3/getting-started.md
> +[https://github.com/LaroldsJubilantJunkyard/galactic-armada](https://github.com/LaroldsJubilantJunkyard/galactic-armada)
Updating with later change. Source code moved to gb-asm-tutorial repo.

2023-05-16 21:24 UTC, LaroldsJubilantJunkyard commented on src/part3/getting-started.md
> +[https://github.com/LaroldsJubilantJunkyard/galactic-armada](https://github.com/LaroldsJubilantJunkyard/galactic-armada)
Done

2023-05-20 02:57 UTC, LaroldsJubilantJunkyard commented on src/part3/spawning-enemies.md
> +For spawning enemies, we increase a counter each frame. When this counter reaches a set value, we’ll TRY to spawn an enemy. If an enemy is actual spawned, we’ll reset the counter. When trying to spaw
i'm not sure what you mean by this..

2023-05-29 08:15 UTC, LaroldsJubilantJunkyard commented on src/part3/the-player.md
> +When an enemy damages the player, we want to decrease our lives by one and start flashing. Later, we'll draw the player's metasprite based on that flashing variable. In the gameplay game state, if we
Changed to 

> That's the end our our "UpdatePlayer" function. The final bit of code for our player handles when they are damaged. When an enemy damages the player, we want to decrease our lives by one. We'll also start flashing  by giving our 'mPlayerFlash' variable a non-zero value. In the gameplay game state, if we've lost all lives, gameplay will end.

2023-05-29 08:26 UTC, LaroldsJubilantJunkyard commented on src/part3/story-screen.md
> +We use that function in the "UpdateStoryState" function, by setting two things:
How about

> We'll use the "DrawText_WithTypewriterEffect" function by setting these registers:

or

> We'll call the "DrawText_WithTypewriterEffect" function exactly how we called the "DrawTextTilesLoop" function. We'll pass this function which tile to start on in `de`, and the address of our text in `hl`.

2023-05-29 08:39 UTC, LaroldsJubilantJunkyard commented on src/part3/object-pools.md
> +Galactic Armada will have “arrays” of bullets and enemies. These “arrays” aren’t what some developers might think. Especially if you come from a javascript background. These “arrays” are really objec
changing to: 

> Galactic Armada will use "object pools" for bullets and enemies. A fixed amount of bytes representing a specific maximum amount of objects. Each pool is just a collection of bytes. The number of bytes per “pool” is the maximum number of objects in the pool, times the number of bytes needed for data for each object.

2023-05-29 08:40 UTC, LaroldsJubilantJunkyard commented on src/part3/spawning-enemies.md
> +For spawning enemies, we increase a counter each frame. When this counter reaches a set value, we’ll TRY to spawn an enemy. If an enemy is actual spawned, we’ll reset the counter. When trying to spaw
That file is now obsolete, will remove it.

2023-06-23 12:20 UTC, ISSOtm commented
I ought to at least leave a comment here, then.

I've basically dreaded reviewing this PR for a few reasons, hence my silence. Despite that I am *really* thankful that Larold put all of this effort, but I'm afraid e.g. of things being redundant with what's planned for the remainder of Part II. I don't want to leave a review because I don't want the effort to feel wasted.

Thus, I haven't dared look at the contents either.

2023-06-23 12:46 UTC, LaroldsJubilantJunkyard commented
> I ought to at least leave a comment here, then.
> 
> I've basically dreaded reviewing this PR for a few reasons, hence my silence. Despite that I am _really_ thankful that Larold put all of this effort, but I'm afraid e.g. of things being redundant with what's planned for the remainder of Part II. I don't want to leave a review because I don't want the effort to feel wasted.
> 
> Thus, I haven't dared look at the contents either.

No worries mate!

A) you can just leave it be and not use it. that's fine.
B) you can post it, but leave a comment at the start about it being new and needing review

I'm very willing to help, update, and make changes/additions. But don't feel obliged. My mind has moved on to other projects. If you choose not to implement, i won't really notice.

It's up to you guys. If there's anything you need, let me know.

2023-06-23 12:51 UTC, avivace commented
> I ought to at least leave a comment here, then.
> 
> I've basically dreaded reviewing this PR for a few reasons, hence my silence. Despite that I am _really_ thankful that Larold put all of this effort, but I'm afraid e.g. of things being redundant with what's planned for the remainder of Part II. I don't want to leave a review because I don't want the effort to feel wasted.
> 
> Thus, I haven't dared look at the contents either.

Thanks, ISSO.

Claiming redundancy with something that has only been "planned" but it's not being actively worked on it's a factor we should completely ignore right now. Part 2 will be worked on when / if people will decide to try to contribute. Until then, something "planned"  there is very far from reality and feasibility (reviewers?) so it shouldn't be considered when reviewing here.

Let me be more precise about what we would need here:

1. Do you see something major that should be corrected? E.g. some bad patterns or bad practices in the code?
2. Do you see something that should be corrected before getting more improved interactions? (e.g. some suggested logic?)
3. Do you see something wrong about starting to merge this, improve/iterate on it and have things eventually overlap/merge with the contents of Part 2?

IMO this part is already quite good and provides tons of additional pointers on top of what we already have (already have, not planned to have).

@LaroldsJubilantJunkyard is also being amazing, and he's very open to suggestions and has shown a rare commitment to keep working on this, accepting feedback and implementing it promptly, it would be a huge waste to ignore his work or let this go inactive because "stuff overlaps with some plans nobody has the intention to work on in the next future".

2023-07-04 20:15 UTC, ISSOtm commented
So as I mentioned via IM, I still haven't finished reviewing everything, but dropping all of the comments and questions I have in a single block would be pretty bad UX so to speak.

So, one thing at a time.

## Tutorial structure / contents

Indeed, this may not be what I had in mind for Part III, or it may happen to be (that would be a happy coincidence!).

But that doesn't really matter, because part of the contract of 1) having other people write the tutorial, and 2) moving the repo under `gbdev` was that compromises would have to be made.

So I would rather accept Larold's work, because they put a lot of effort into contributing to a community resource, and that the tutorial would be worse off just incomplete. I think.

## Makefile

I've looked at the Makefile structure, and frankly I'm a little puzzled. It seems to bypass the normal build graph mechanism to instead try and treat Make more as a shell script.

I wouldn't mind that as-is, but it seems to be more complex, and also nullify Make's "only rebuild what needs to be" feature, which I think is not something we should show in a tutorial after which people will pattern their actual projects.

However, maybe I missed a specific reason it's done this way?

2023-07-04 21:33 UTC, eievui5 commented
re: Makefile

Even if there’s a reason for it to be structured incorrectly, we absolutely need to rewrite it so that it works as expected. Make was chosen specifically because of the features it has which make gbdev easier. I think gb-boilerplate’s makefile (stripped down if needed) should be used and the project needs to be restructured accordingly

2023-07-07 13:38 UTC, avivace commented
> re: Makefile
> 
> Even if there’s a reason for it to be structured incorrectly, we absolutely need to rewrite it so that it works as expected. Make was chosen specifically because of the features it has which make gbdev easier. I think gb-boilerplate’s makefile (stripped down if needed) should be used and the project needs to be restructured accordingly

Do we have examples or directions on how such a makefile should be structured? Your (and @ISSOtm ) comments on the Makefile seem to say "it's wrong/should standardized" but they don't seem to provide corrections or ideas on how to correct/what's specifically wrong about it. Can we try to move this forward with some suggestion?

2023-07-07 13:44 UTC, avivace commented
> Indeed, this may not be what I had in mind for Part III, or it may happen to be (that would be a happy coincidence!).
> 
> But that doesn't really matter

@ISSOtm The problem is: it _does_ matter, and we're waiting on you to provide feedback (or even any kind of formalisation) on what is that you have in mind from I don't know how much time that the tutorial got stuck between overlaps of blocking "ideas"/"plans" that are not even formalized yet. This literally blocks the resource.

We don't want the tutorial to follow your vision/ideas because of a "coincidence" (that you are happy to accept just because someone worked on it?). This really sends the wrong message.

We want the process of formalizing, discussing and exchanging ideas and opinions to be the reason why the tutorial explains A doing B in a C way. None of this can be done if you don't provide practical examples (or even vague formalisations) of your plan.

So please, tell us your ideas/vision and which way this part may or may not be implementing them. That's the only thing we need to go forward. In absence of that (or your leadership) this gets blocked and we're back at square one.

2023-07-07 18:15 UTC, eievui5 commented
> Do we have examples or directions on how such a makefile should be structured? Your (and @ISSOtm ) comments on the Makefile seem to say "it's wrong/should standardized" but they don't seem to provide corrections or ideas on how to correct/what's specifically wrong about it. Can we try to move this forward with some suggestion?

i did make a suggestion: we should use gb-boilerplate’s makefile, removing some features if needed.

2023-07-07 19:47 UTC, avivace commented
> gb-boilerplate

Thanks @eievui5 . @LaroldsJubilantJunkyard can you check https://github.com/ISSOtm/gb-boilerplate and see if it could be applicable to the project files here?

2023-07-07 20:04 UTC, ISSOtm commented
I wrote what I thought about the Makefile design, and GitHub's mobile app didn't send it. Great.

---

The structural problem I have with the Makefile is that the top-level rule is intended to run four steps in parallel (clean, convert gfx files, copy sources to `obj`, and build the ROM). This bypasses/abuses Make's dependency graph, which is not a practice I think we should recommend, especially because I believe it would break with parallel builds (`-j`).

I did not suggest any alternatives, because I wanted to give @LaroldsJubilantJunkyard a chance to defend his design before suggesting a replacement (see the last line of my previous message). I was afraid that it would be discouraging and/or demeaning.

I do not think that we should use gb-boilerplate, as its Makefile has extra complexity in order to automatically detect dependencies (and it's known to be unstable depending on the version of Make, though Make 4.4 maybe finally explains why). However, the general idea remains the same: merely describe dependency relations & build recipes, and let Make do its thing of figuring out in which order to build what. The difference with gb-boilerplate being that we'd specify everything manually, to keep it relatively simple.

2023-08-19 04:02 UTC, ZoomTen requested changes
I've got my own suggestions on the Makefile&hellip;

There are separate targets now which I hope is compatible with parallel building, though it *does* make the resulting Makefile a bit more complicated.

Maybe it would help somehow if we can explain the complexity, what with all the random sigils and functions thrown everywhere as is expected of a Makefile? In the interest of Doing It Right:tm:, of course...

2023-08-19 06:55 UTC, ZoomTen commented on galactic-armada/Makefile
> +	mkdir -p $(DSTDIR)
```suggestion
define ensure-directory
$1:
	mkdir -p $$@
endef

PREPARE_DIRECTORIES = \
	$(OBJDIR) $(GENSPRITES) $(GENBACKGROUNDS) $(DSTDIR)

$(foreach i, $(PREPARE_DIRECTORIES), $(eval $(call ensure-directory,$i)))
```
Define one target each for prepared directories.

2023-08-19 10:18 UTC, ISSOtm commented
Regarding the Makefile, I have a few primary suggestions right now. Most of them revolve around making the Makefile drastically simpler, following the theme of introducing new concepts incrementally.

- Remove the `SRCDIR` variable. The point of variables like `OBJDIR` is to allow building out-of-tree in a flexible location; however, it makes imo no sense to allow pointing the Makefile at a *different* source tree, since it's inherently part of it.
- Use `${}` for variables instead of `$()`. This helps differentiate them from function calls (which only accept the latter syntax); this is especially useful when both kinds are nested.
- Remove all of the `*DIR` and `RGB*` variables. For a "directed" project like this, it should be fine to hardcode all paths; this will notably remove one layer of indirection, and allow the reader to familiarise themselves with what that layer of indirection will "resolve" to. (There may be a case for keeping all of the `RGB*` variables, in case someone doesn't have RGBDS in their path, or under different names? Idk.)
- Build in-tree. Building out-of-tree is better for a lot of reasons, but adds significant complexity (creating output directories, doing more path substitution instead of just extension rewriting, etc.). Again, since this is a "controlled environment", it should be fine to do things slightly dirty if it helps introducing concepts gradually; additionally, I believe experiencing the downsides of in-tree builds should help justify the extra complexity of out-of-tree builds when they're introduced later.

Of course, the question is then "sure, but when do we introduce all of those? Part 3 is the last one!"; to which the answer I'd give is to make an additional Part 4. (I think not building a full game in that one, but just guiding through the creation of a *template*, should be sufficient. That said, if this idea sounds good to other people, I should open a separate issue to discuss it and not derail this already lengthy PR.)

2023-08-19 10:59 UTC, ISSOtm commented
Note: I haven't submitted a Makefile applying the above points because I thought it'd be better to discuss them first. But I can also write one if that's preferred.

2023-08-20 10:33 UTC, avivace requested changes

2023-08-20 10:33 UTC, avivace commented on galactic-armada/Makefile
> +OBJS       = $(ASMSOURCES_COLLECTED:%.asm=$(OBJDIR)/%.o)
```suggestion
OBJS = $(patsubst %.asm,$(OBJDIR)/%.o,$(notdir $(ASMSOURCES_COLLECTED)))
```

2023-08-21 07:17 UTC, ZoomTen approved these changes
Looks good for now I'd say, we can iterate on it over time

2023-08-21 09:09 UTC, avivace approved these changes

2023-08-21 09:55 UTC, merged