Attribute copyright to contributors as well
gbdev/gb-asm-tutorial pull request #62
Opened 2023-07-04 20:06 UTC by ISSOtm

Part one of #58.

2023-07-05 18:07 UTC, avivace requested changes

2023-07-05 18:07 UTC, avivace commented on LICENSE
> +Copyright (c) 2021 Eldred Habert and contributors
What about:

```suggestion
Copyright (c) 2021 - 2023 gb-asm-tutorial contributors
```

and we create an "AUTHORS" file in the root of the repository? We should still decide where those names can be added in the tutorial itself..

2023-07-07 12:57 UTC, ISSOtm commented on LICENSE
> +Copyright (c) 2021 Eldred Habert and contributors
```suggestion
Copyright © 2021–2022 Eldred Habert
Copyright © 2022–2023 gb-asm-tutorial contributors
```
(Based on 8b3e24b27c9aa8392c28f233b9681c48c16cea59 being the first commit that contributed significant content.)

Should we do attribution inside the repo itself, or should we defer to the Git info (e.g. [GitHub's "contributors" page](https://github.com/gbdev/gb-asm-tutorial/graphs/contributors)?

In the former case, we should determine what qualifies someone to enter the file. Additionally, I'd make it a ` .md`  file, and `{{#include}}` it in the "credits" page.

2023-08-23 00:45 UTC, avivace approved these changes

2023-08-23 00:45 UTC, merged