II-17: Initializing wCurKeys and wNewKeys
gbdev/gb-asm-tutorial pull request #76
Opened 2024-02-01 18:44 UTC by kav

Fixes #75

2024-02-01 18:50 UTC, avivace approved these changes

2024-02-01 19:26 UTC, eievui5 commented
These `ld`s should be on the other side of the "Main" anchor

2024-02-01 19:28 UTC, eievui5 commented
Oh, there isn't an "init" anchor for this chapter. I think the chapter itself needs to be corrected, not just this code

2024-02-01 19:44 UTC, kav commented
Yeah I put them there so they'd be set as part of updating main but I can add an init section instead after we define them if you'd prefer

2024-02-01 19:49 UTC, eievui5 commented
Yeah, that sounds best. Something like this:

> We also need to initialize these when our game starts, so add two more lines:
> ```
> 	; Turn the LCD on
> 	ld a, LCDCF_ON | LCDCF_BGON | LCDCF_OBJON
> 	ld [rLCDC], a
> 
> 	; During the first (blank) frame, initialize display registers
> 	ld a, %11100100
> 	ld [rBGP], a
> 	ld a, %11100100
> 	ld [rOBP0], a
> 
> 	ld a, 0
> 	ld [wFrameCounter], a
> 	ld [wCurKeys], a
> 	ld [wNewKeys], a
> ```

I think diff syntax would help highlight the new lines but I'm not sure if the leading + signs would be confusing--do we use diffs anywhere else?

2024-02-02 01:49 UTC, kav commented
Diff syntax doesn't show up until adding the brick check two sections later.
```
+	call CheckAndHandleBrick
```

I'm inclined to instead introduce variable initialization with a sentence and  a comment when initialize the frame counter and then refer to that here. 

I think diff syntax would probably be ok here but let me try the other approach first. As a new reader with fresh eyes on all this I think that would make more sense to me.

2024-02-11 18:07 UTC, ISSOtm commented
> I can take care of this for you if I have permission to edit your fork.

Since you don't have upstream push access (something maybe we should consider? cc @avivace), an alternative is to suggest the modifications using review comments (they have an exclusive "suggest changes" feature); then it's "only" a two-click operation for the author.

2024-02-11 18:13 UTC, ISSOtm requested changes
Thank you! The change's contents look good to me; I would just like to tweak a few things before accepting it.

Though, @eievui5 mentioned that the chapter needs something rewritten? If you could look into that, then I wouldn't mind integrating the fix into this PR; but if you can't or don't want to in the next few weeks or so, then we can open a separate issue for it.

2024-02-11 18:13 UTC, ISSOtm commented on src/part2/input.md
> +Before we read these variables we will also want to initialize them. We can do that below our initialization  of `wFrameCounter`.
```suggestion
Before we read these variables we will also want to initialize them.
We can do that below our initialization  of `wFrameCounter`.
```

Just a style nitpick.

2024-02-11 18:13 UTC, ISSOtm commented on unbricked/bricks/main.asm
> +	; Initialize variables
```suggestion
	; Initialize global variables
```
I think it's important to highlight what variables need to be initialised at this point. (A good rule of thumb is "initialise as close as possible to the point of usage".)

(Note: this change would have to be applied to the other instances as well.)

2024-02-12 00:34 UTC, avivace approved these changes

2024-02-12 00:37 UTC, avivace commented
> Thank you! The change's contents look good to me; I would just like to tweak a few things before accepting it.
> 
> Though, @eievui5 mentioned that the chapter needs something rewritten? If you could look into that, then I wouldn't mind integrating the fix into this PR; but if you can't or don't want to in the next few weeks or so, then we can open a separate issue for it.

I'd suggest we merge this and limit the scope of this PR. Evie also already has "maintain" access to this repository.

2024-02-16 10:01 UTC, ISSOtm approved these changes
Then let's merge this improvement as it is :)

I'll let @eievui5 create an issue or PR with the changes she deems appropriate ^^

2024-02-16 10:02 UTC, merged

2024-02-16 10:02 UTC, ISSOtm commented
Thank you @kav!