Fixing two small typos that I encountered while learning
gbdev/gb-asm-tutorial pull request #77
Opened 2024-02-02 02:09 UTC by kav

II Objects: Adding line numbers to clear-oam
II WIP: noting section III is Arkanoid

2024-02-02 07:40 UTC, avivace approved these changes

2024-02-08 10:56 UTC, ISSOtm requested changes
Thank you for the PR!

2024-02-08 10:56 UTC, ISSOtm commented on src/part2/wip.md
> +As explained in the initial tutorial presentation, Part Ⅲ consists of us building an *Arkanoid* game.
*Arkanoid* is a block-breaking game, like *Breakout*, and that's what Part II is supposed to cover. Is there a misunderstanding here?

2024-02-08 17:10 UTC, kav commented on src/part2/wip.md
> +As explained in the initial tutorial presentation, Part Ⅲ consists of us building an *Arkanoid* game.
Oh yeah, of course, I forgot that was the name.
Most of my experience the game was with breakout on the 68k Macs. I'll pull that line in a few or you are welcome to update the pr

2024-02-09 09:49 UTC, avivace approved these changes

2024-02-09 09:50 UTC, merged